server:
  port: 57777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bojiang?useSSL=true&serverTimezone=UTC
    username: temp
    password: 123
bojiang:
  search-zhubo-url-pattern: https://www.bojianger.com/data/api/common/search_anchor_new.do?keyword={keyword}&pageNum=1&pageSize=5&keywordMark={keyword}
  url-pattern: https://www.bojianger.com/data/api/auth/anchor_detail_danmu.do?date={date}&rid={rid}&uid=0&order=-1&time=-1&duration=0+~24&pageNum={pageNum}&pageSize=20
  stat-url-pattern: https://www.bojianger.com/data/api/auth/anchor_detail_total.do?date={date}&rid={rid}
  start-date: 2023-02-01

mybatis:
  mapper-locations:
    - classpath:mapper/**.xml