server:
  port: 60200
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: CircuitBreaker
          args:
            name: testA
            fallbackUri: forward:/myFallback
        - name: Retry
          args:
            retries: 100
            methods:
              - GET
            statuses:
              - INTERNAL_SERVER_ERROR

resilience4j:
  circuitbreaker:
    configs:
      testA:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 9
        failureRateThreshold: 33
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 50s
  timelimiter:
    configs:
      testA:
        timeoutDuration: 3s
        cancelRunningFuture: true




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:60000/eureka/