server:
  port: 60040
spring:
  application:
    name: user-service
#  config:
#    import: optional:configserver:http://localhost:60020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:60000/eureka/