spring:
  datasource:
    url: jdbc:mysql://localhost:3306/huaban?useSSL=true&serverTimezone=UTC
    username: temp
    password: 123
huaban:
  user:
    ai-url-pattern: https://api.huaban.com/search/scene?filter_ids[]={filter}&filter_ids[]=5871245&page={page}&position=search_aigc&sort=all
    discovery-url-pattern: https://api.huaban.com/pins/recommend/winnow?page_num={pageNum}&page_size=40&position=discovery_recommend
    ui-url-pattern: https://api.huaban.com/pins/recommend/winnow?page_num={pageNum}&page_size=40&category={category}
  board:
    per-count: 30
    url-pattern: https://api.huaban.com/{urlname}/boards?limit={limit}&urlname={urlname}
  pin:
    per-count: 40
    url-pattern: https://api.huaban.com/boards/{boardId}/pins?limit={limit}
    detail-url-pattern: https://api.huaban.com/pins/{pinId}?fields=pin:PIN_DETAIL&pins=20

mybatis-plus:
  mapper-locations:
    - classpath:mapper/**.xml

all-path: D:\Workspace\Java\idea\product\noah\huaban-service\src\main\resources\all.txt
done-path: D:\Workspace\Java\idea\product\noah\huaban-service\src\main\resources\done.txt
failed-path: D:\Workspace\Java\idea\product\noah\huaban-service\src\main\resources\failed.txt
exit-path: D:\tmp\status\exit-8080.txt
threads: 10
date-limit: 2023-01-01
cookie: sid=s%3Axe76G60rRlWDfxaZWTWtza4uc7J4vR1Z.FXeqlO9rx0K9hR0fYPEbMbWrRezWRyT9t5qenz8CQMk; user_device_id=dd2d761ff2ba49688db16a5b175396c5; user_device_id_timestamp=1688861021189; Hm_up_d4a0e7c3cd16eb58a65472f40e7ee543=%7B%22version%22%3A%7B%22value%22%3A%222.0.0%22%2C%22scope%22%3A1%7D%2C%22has_plugin%22%3A%7B%22value%22%3A%220%22%2C%22scope%22%3A1%7D%7D; uid=37092102; gd_id=2024750070078524489; Hm_lvt_d4a0e7c3cd16eb58a65472f40e7ee543=1689164360,1689590528,1689635206,1689725902; _gid=GA1.2.416986400.1689725903; acw_tc=0bde431216897259033247748e66275793320f5201b8fe0c2e731a7fcf28b3; _gat_UA-135559536-2=1; Hm_lpvt_d4a0e7c3cd16eb58a65472f40e7ee543=1689726013; _ga_50RYEM7F09=GS1.1.1689725902.23.1.1689726013.0.0.0; _ga=GA1.1.976951187.1688860984